name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: ourschool
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # استخدم إصدار PHP المطلوب
          extensions: mbstring, xml, mysql, bcmath # أضف أي ملحقات تحتاجها

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Database Migrations
        run: |
          php artisan migrate --env=testing

      - name: Run Unit Tests
        run: php artisan test

      - name: Deploy to Server
        if: github.ref == 'refs/heads/main' # قيادة إلى نشر على الفرع الرئيسي
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "cd ${{ secrets.DEPLOY_PATH }} && git pull origin main && composer install && php artisan migrate --force"
